### ISSUE TITLE
Highlight only Dragging UICollectionViewCell

### ISSUE THREAD

**Issue by shahdhiren** [mmick66/KDRearrangeableCollectionViewFlowLayout#2]
I want that only the cell which is currently being dragged should be changing the background color. I tried manupulating few code in handleGesture() method and in delegate methods of the UICollectionView, but didn't succeeded. 

Can you please help me how to achieve this with current code?

**Comment by mmick66** [comment]
Please checkout the new commit. I am performing the change that you asked. There is a small flicker but if this is acceptable for the moment I can close this issue and work on it later. Please let me know.

**Comment by mmick66** [comment]
I just pushed a fix to the flicker problem outlined above. This should finally close this issue. You can override the dragging property of the cell to customise the look that you want for the snapshot that is going to be dragged around.
