### ISSUE TITLE
Preventing cells to get dragged vertically (only horizontal)

### ISSUE THREAD

**Issue by sentiasa** [mmick66/KDRearrangeableCollectionViewFlowLayout#3]
Great Library! Thanks a lot for sharing it!

I have a question. Suppose that I have 4 cells in one line (so I can see them in a row without need of scrolling). Is there a way to lock the cells to get dragged in the X axis and only Y axis? So prevent vertical movements of the collectionViewCells and strict them to get dragged horizontally only.

**Comment by mmick66** [comment]
I just added a constraint on the dragging through a property called "axis". Try the following

```
override func viewDidLoad() {      
   super.viewDidLoad()
   self.collectionViewRearrangeableLayout.draggable = true
   self.collectionViewRearrangeableLayout.axis = .X // constraint on the x axis
}
```

**Comment by sentiasa** [comment]
Thanks a lot man! Works like charm!
Hope this library gets the recognition it deserves
