### ISSUE TITLE
Instance of the Layout is not getting released

### ISSUE THREAD

**Issue by cashish** [mmick66/KDRearrangeableCollectionViewFlowLayout#5]
Thanks a lot for great Library.

we have a issue in releasing the instance of KDRearrangeableCollectionViewFlowLayout layout and cells but controller get releases. if we do not use this layout then everything works fine. 
![screen shot 2016-05-27 at 10 52 04 am](https://cloud.githubusercontent.com/assets/3477870/15598639/ad903f14-23f9-11e6-8bda-50a97199152c.png)

**Comment by mmick66** [comment]
Can you please show me some code? I do not understand what you mean by releasing the layout.

**Comment by cashish** [comment]
You can see in below screenshot, In the Persistent field   we have a issue in releasing the  KDRearrangeableCollectionViewFlowLayout and cells but controller get releases. You can see in below screenshot 
![screen shot 2016-05-27 at 10 52 04 am](https://cloud.githubusercontent.com/assets/3477870/15768628/1d9eef78-2970-11e6-8566-271b9abb065a.png)

**Comment by mmick66** [comment]
You could send me the project in a zip file here and I will take a look.

**Comment by cashish** [comment]
Please find the zip file 
[KDRearrangeableCollectionViewFlowLayout.zip](https://github.com/mmick66/KDRearrangeableCollectionViewFlowLayout/files/313160/KDRearrangeableCollectionViewFlowLayout.zip)

**Comment by cashish** [comment]
please find the attached zip file
[KDRearrangeableCollectionViewFlowLayout.zip](https://github.com/mmick66/KDRearrangeableCollectionViewFlowLayout/files/313161/KDRearrangeableCollectionViewFlowLayout.zip)

**Comment by mmick66** [comment]
Sorry for the delay. I cannot seem to make it crash. Can you please let me know the steps to reproduce?
