### ISSUE TITLE
OC

### ISSUE THREAD

**Issue by CYZZ** [mmick66/KDRearrangeableCollectionViewFlowLayout#6]
did demo with OC

**Comment by mmick66** [comment]
What are you trying to say?

**Comment by CYZZ** [comment]
Language Swift translate to Object-C

**Comment by mmick66** [comment]
Are you telling **_me_** to translate it to Objective-C!?

**Comment by CYZZ** [comment]
YES,I’m poor in english,sorry.

**Comment by mmick66** [comment]
Ok, I cannot re-write it in Objective-C, this is entirely another project. The reason I give the code open source is so that others can contribute based on that and hopefully make it better (apart from being happy to share that is ;-). So maybe you want to do that and create a pull request.
