### ISSUE TITLE
Add this playground implementation?

### ISSUE THREAD

**Issue by SmatchyLaPaglia** [mmick66/KDRearrangeableCollectionViewFlowLayout#7]
I wrote an implementation of this in a playground, which required removing all the dependencies on storyboards.

Maybe you could add it to the project as a demo? I struggled a lot to make it work, so I know it would be helpful to some people as an example of how to use this class programmatically.

[KDRearrangeablePlayground.playground.zip](https://github.com/mmick66/KDRearrangeableCollectionViewFlowLayout/files/302668/KDRearrangeablePlayground.playground.zip)

**Comment by mmick66** [comment]
Sure man... Can you do a pull request please?

**Comment by SmatchyLaPaglia** [comment]
Sorry to drop this--I think there are now built-in methods that accomplish this, so my Playground is moot.
